version: 2.1

#on: [push, pull_request]


jobs:
  build-linux:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          command: |
            echo Building Linux Version
            cmake .
            make

workflows:
  build-workflow:
    jobs:
      - build-linux
